#!/usr/bin/env python3
"""Turn a short video of your avatar into sprite sheets for the PSP.

    uv run --with pillow --with numpy tools/pack_video.py VIDEO

The video should show one character on a plain, near-white background. This
samples it at the app's frame rate, crops to the character, cuts the
background out with a soft matte so fine edges survive, cross-fades the end
into the start so the loop has no jump, and packs the frames into 512x512
sheets, the largest texture the PSP can use.

The frames land in assets/clip, which git ignores, so your artwork stays out
of the repository. Use a video you have the right to use.
"""
import pathlib
import subprocess
import sys
import tempfile

import numpy as np
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "clip"
FPS = 10
CELL_W, CELL_H = 168, 256       # three across and two down fill a 512x512 sheet
COLUMNS, ROWS = 3, 2
PAD = 10                        # source pixels kept around the character
# Colour distance from the background: clear below the first, solid above the
# second. The low end sits above the video's compression noise, which
# otherwise leaves a faint box around the character.
MATTE_LOW, MATTE_HIGH = 14, 44
BLEND_FRAMES = 6                # frames at the end cross-faded toward the first
# The PSP holds each sheet at 4 bits a channel, half the memory of 8. Cut
# straight down, the soft fur turns to bands, so the rounding is spread with
# a fixed pattern. Being fixed, it does not shimmer from frame to frame.
BAYER = np.array([[0, 32, 8, 40, 2, 34, 10, 42], [48, 16, 56, 24, 50, 18, 58, 26],
                  [12, 44, 4, 36, 14, 46, 6, 38], [60, 28, 52, 20, 62, 30, 54, 22],
                  [3, 35, 11, 43, 1, 33, 9, 41], [51, 19, 59, 27, 49, 17, 57, 25],
                  [15, 47, 7, 39, 13, 45, 5, 37], [63, 31, 55, 23, 61, 29, 53, 21]]) / 64.0


def to_4_bits(image):
    """Every channel dithered down to 16 levels, written back as 0, 17 ... 255."""
    pixels = np.asarray(image, dtype=np.float64)
    h, w, _ = pixels.shape
    pattern = np.tile(BAYER, (h // 8 + 1, w // 8 + 1))[:h, :w, None]
    out = np.clip(np.floor(pixels / 17.0 + pattern), 0, 15) * 17
    out[..., 3] = np.where(pixels[..., 3] < 8, 0, out[..., 3])
    return Image.fromarray(out.astype(np.uint8), "RGBA")


def main():
    video = pathlib.Path(sys.argv[1])
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(["ffmpeg", "-v", "error", "-i", str(video), "-vf", "fps=%d" % FPS,
                        tmp + "/%03d.png"], check=True)
        frames = [np.asarray(Image.open(p).convert("RGB"), dtype=np.float32)
                  for p in sorted(pathlib.Path(tmp).glob("*.png"))]

    h, w, _ = frames[0].shape
    background = np.median(np.concatenate([f[:6].reshape(-1, 3) for f in frames]), axis=0)

    def distance(frame):
        return np.abs(frame - background).sum(axis=2)

    solid = np.zeros((h, w), dtype=bool)
    for frame in frames:
        solid |= distance(frame) > 40
    ys, xs = np.where(solid)
    left, right = max(xs.min() - PAD, 0), min(xs.max() + PAD, w)
    top, bottom = max(ys.min() - PAD, 0), min(ys.max() + PAD, h)

    count = len(frames)
    for i in range(BLEND_FRAMES):
        t = (i + 1) / (BLEND_FRAMES + 1)
        index = count - BLEND_FRAMES + i
        frames[index] = frames[index] * (1 - t) + frames[0] * t

    cells = []
    scale = min(CELL_W / (right - left), CELL_H / (bottom - top))
    size = (round((right - left) * scale), round((bottom - top) * scale))
    for frame in frames:
        alpha = np.clip((distance(frame) - MATTE_LOW) / (MATTE_HIGH - MATTE_LOW), 0, 1)
        rgba = np.dstack([frame, alpha * 255]).astype(np.uint8)[top:bottom, left:right]
        fitted = Image.fromarray(rgba, "RGBA").resize(size, Image.Resampling.LANCZOS)
        cell = Image.new("RGBA", (CELL_W, CELL_H), (0, 0, 0, 0))
        cell.paste(fitted, ((CELL_W - size[0]) // 2, CELL_H - size[1]))
        cells.append(cell)

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.png"):
        old.unlink()
    per_sheet = COLUMNS * ROWS
    sheets = (len(cells) + per_sheet - 1) // per_sheet
    for s in range(sheets):
        sheet = Image.new("RGBA", (512, 512), (0, 0, 0, 0))
        for i, cell in enumerate(cells[s * per_sheet:(s + 1) * per_sheet]):
            sheet.paste(cell, ((i % COLUMNS) * CELL_W, (i // COLUMNS) * CELL_H))
        to_4_bits(sheet).save(OUT / ("%02d.png" % s), optimize=True)

    (ROOT / "app" / "clip_table.h").write_text(
        "/* Generated by tools/pack_video.py. Do not edit. */\n"
        "#define CLIP_FRAMES %d\n#define CLIP_SHEETS %d\n#define CLIP_FPS %d\n"
        "#define CLIP_CELL_W %d\n#define CLIP_CELL_H %d\n#define CLIP_COLUMNS %d\n#define CLIP_ROWS %d\n"
        "#define CLIP_BG_R %d\n#define CLIP_BG_G %d\n#define CLIP_BG_B %d\n"
        % (len(cells), sheets, FPS, CELL_W, CELL_H, COLUMNS, ROWS, *[round(c) for c in background]))
    total = sum(p.stat().st_size for p in OUT.glob("*.png"))
    print("%d frames in %d sheets, %.0f KB, character %dx%d px, background %s"
          % (len(cells), sheets, total / 1024, size[0], size[1], [round(c) for c in background]))


if __name__ == "__main__":
    main()
